name: Enhancement
description: >-
  If you want a new feature or an enhancement of an existing feature,
  please use this template.
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you want.
      placeholder: As a user, I want to be able to...
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
